# Config file for automatic testing at travis-ci.org

# Note that local tests with tox do not use this config file.
# See tox.ini file instead.

language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

install: pip install -r requirements.txt

# command to run tests
script: coverage run tests/test_minimalmodbus.py

# Command for online test coverage analysis
before_install:
  pip install codecov

after_success:
  codecov
